name: codeCov

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - converted_to_draft
  workflow_dispatch:
    inputs:
      test_project:
        description: 'Test project to run (leave empty for all)'
        required: false
        default: ''
        type: string

jobs:
  test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Adjust version as needed
          
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.26
        
      - name: Test with coverage
        id: test
        run: dotnet test MinimapApi --configuration Release --verbosity normal --logger "trx;LogFileName=testresults.trx" --collect:"XPlat Code Coverage"
        
      - name: Test Report
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # 1.9.1
        if: always()
        with:
          name: Unit Test
          path: "**/testresults.trx"
          reporter: dotnet-trx
          fail-on-error: true
        
      - name: Generate coverage report
        run: |
          reportgenerator \
          -reports:**/TestResults/**/coverage.cobertura.xml \
          -targetdir:coverage \
          -reporttypes:Cobertura
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/Cobertura.xml
          fail_ci_if_error: true
